{% set name = "tokenizers" %}

package:
  name: "{{ name|lower }}"
  version: "{{ TOKENIZERS_VERSION }}"

source:
  path: ../../

requirements:
  host:
    - pip
    - python x.x
    - setuptools
    - setuptools-rust
    - pkg-config
    - openssl
    - maturin

  run:
    - python x.x
    - huggingface_hub <1.0

test:
  imports:
    - tokenizers
    - tokenizers.models

about:
  home: https://huggingface.co/docs/tokenizers
  license: Apache License 2.0
  license_file: LICENSE
  summary: "💥 Fast State-of-the-Art Tokenizers optimized for Research and Production"
